"""Constants for the HelvarNet integration."""

DOMAIN = "helvar"

CONF_HOST = "host"
CONF_PORT = "port"
CONF_CLUSTER_ID = "cluster_id"
CONF_ROUTER_ID = "router_id"

DEFAULT_PORT = 50000

DEFAULT_ON_GROUP_SCENE = 1
DEFAULT_ON_GROUP_BLOCK = 1
DEFAULT_OFF_GROUP_BLOCK = 1
DEFAULT_OFF_GROUP_SCENE = 15
VALID_OFF_GROUP_SCENES = (15, 16)
